name: EEGAnalysis
channels:
  - plotly
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - cython
  - ffmpeg
  - h5py
  - hdf5
  - ipython
  - ipywidgets
  - jupyter
  - numpy
  - pandas
  - pip
  - plotly
  - scikit-learn
  - scipy
  - tqdm
  - matplotlib
  - pip:
    - future
    - seaborn

